name: CD deploy main
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push main image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: proceda/twenty:latest,proceda/twenty:${{ github.sha }}

      - name: Build and push postgres image
        uses: docker/build-push-action@v4
        with:
          context: ./packages/twenty-postgres
          push: true
          tags: proceda/twenty-postgres-spilo:latest,proceda/twenty-postgres-spilo:${{ github.sha }}