name: CD deploy main
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push with docker-compose
        run: |
          # Set the TAG environment variable to the commit SHA
          export TAG=${{ github.sha }}
          
          # Build and push the images
          docker-compose -f packages/twenty-docker/docker-compose.yml build
          docker-compose -f packages/twenty-docker/docker-compose.yml push
          
          # Tag and push latest
          docker tag proceda/twenty:${TAG} proceda/twenty:latest
          docker tag proceda/twenty-postgres-spilo:${TAG} proceda/twenty-postgres-spilo:latest
          docker push proceda/twenty:latest
          docker push proceda/twenty-postgres-spilo:latest
