name: Docker Publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Generate version
        id: version
      - name: Create Git tag for main branch
        if: github.ref == 'refs/heads/main'
        run: |
          VERSION=${{ steps.version.outputs.version }}
          git tag -a "v${VERSION}" -m "Automated tag for version ${VERSION}"
          git push origin "v${VERSION}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            VERSION=$(date +'%Y%m%d')-$(git rev-parse --short HEAD)
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Extract metadata for Twenty
        id: meta-twenty
        uses: docker/metadata-action@v5
        with:
          images: proceda/twenty
          tags: |
            type=raw,value=${{ steps.version.outputs.version }}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=raw,value=${{ steps.version.outputs.version }}-dev,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Extract metadata for Postgres
        id: meta-postgres
        uses: docker/metadata-action@v5
        with:
          images: proceda/twenty-postgres-spilo
          tags: |
            type=raw,value=${{ steps.version.outputs.version }}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=raw,value=${{ steps.version.outputs.version }}-dev,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
      
      - name: Build and push Twenty Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/twenty-docker/twenty/Dockerfile
          push: true
          tags: ${{ steps.meta-twenty.outputs.tags }}
          labels: ${{ steps.meta-twenty.outputs.labels }}

      - name: Build and push Postgres Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/twenty-docker/twenty-postgres-spilo/Dockerfile
          push: true
          tags: ${{ steps.meta-postgres.outputs.tags }}
          labels: ${{ steps.meta-postgres.outputs.labels }}

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false