name: Docker Publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata for Twenty
        id: meta-twenty
        uses: docker/metadata-action@v5
        with:
          images: proceda/twenty
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha

      - name: Extract metadata for Postgres
        id: meta-postgres
        uses: docker/metadata-action@v5
        with:
          images: proceda/twenty-postgres-spilo
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
      
      - name: Build and push Twenty Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/twenty-docker/twenty/Dockerfile
          push: true
          tags: ${{ steps.meta-twenty.outputs.tags }}
          labels: ${{ steps.meta-twenty.outputs.labels }}

      - name: Build and push Postgres Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/twenty-docker/twenty-postgres-spilo/Dockerfile
          push: true
          tags: ${{ steps.meta-postgres.outputs.tags }}
          labels: ${{ steps.meta-postgres.outputs.labels }}