name: Update Latest Tag

on:
  push:
    branches:
      - main

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update Latest Tag
        run: |
          git tag -f latest
          git push -f origin latest
